#!/usr/bin/env python3
"""Train a BERT-based lawsuit classifier from LLM-generated training data.

This script trains a fast BERT-based multilabel classifier using the training
data generated by zero_shot_classifier.py. The resulting model can classify
lawsuits much faster than the LLM-based approach.

Usage:
    # Train using default config
    python scripts/train_bert_classifier.py

    # Train with custom data
    python scripts/train_bert_classifier.py --data data/custom_training.json

    # Train with custom model
    python scripts/train_bert_classifier.py --model nlpaueb/legal-bert-base-uncased

    # Resume training from checkpoint
    python scripts/train_bert_classifier.py --resume

    # Evaluate on test set
    python scripts/train_bert_classifier.py --evaluate
"""

import argparse
import json
import logging
import sys
import tomllib
from pathlib import Path
from typing import Any

import numpy as np
import torch
from sklearn.metrics import classification_report, hamming_loss, f1_score
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)

# Add parent directory to path for imports
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

logger = logging.getLogger(__name__)


class LawsuitDataset(Dataset):
    """Dataset for lawsuit classification."""

    def __init__(
        self,
        texts: list[str],
        labels: list[list[int]],
        tokenizer,
        max_length: int,
    ):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": torch.tensor(label, dtype=torch.float),
        }


def load_config(config_path: Path) -> dict[str, Any]:
    """Load configuration from TOML file."""
    with open(config_path, "rb") as f:
        config = tomllib.load(f)
    return config.get("lawsuit_classification", {})


def load_training_data(data_path: Path) -> tuple[list[str], list[list[int]], list[str]]:
    """Load and prepare training data from JSON file.

    Returns:
        texts: List of input texts (case metadata + document excerpts)
        labels: List of multilabel binary vectors
        categories: List of category names
    """
    with open(data_path) as f:
        data = json.load(f)

    categories = data["metadata"]["categories"]
    category_to_idx = {cat: idx for idx, cat in enumerate(categories)}

    texts = []
    labels = []

    for result in data["results"]:
        # Build input text from metadata and excerpt
        text_parts = [
            f"Caption: {result.get('caption', 'Unknown')}",
            f"Court: {result.get('court', 'Unknown')}",
            f"Case Type: {result.get('case_type', 'Unknown')}",
        ]

        # Add document names if available
        if result.get("document_names"):
            text_parts.append(f"Documents: {', '.join(result['document_names'])}")

        # Add text excerpt
        if result.get("text_excerpt"):
            text_parts.append(f"\nExcerpt:\n{result['text_excerpt']}")

        text = "\n".join(text_parts)

        # Build multilabel vector
        label_vector = [0] * len(categories)
        for label_info in result.get("labels", []):
            category = label_info["category"]
            if category in category_to_idx:
                label_vector[category_to_idx[category]] = 1

        # Only include if at least one label is present
        if sum(label_vector) > 0:
            texts.append(text)
            labels.append(label_vector)

    logger.info(f"Loaded {len(texts)} training examples")
    logger.info(f"Categories: {categories}")

    # Print label distribution
    label_counts = np.array(labels).sum(axis=0)
    for cat, count in zip(categories, label_counts):
        logger.info(f"  {cat}: {int(count)} examples ({count/len(texts)*100:.1f}%)")

    return texts, labels, categories


def train_epoch(
    model,
    dataloader,
    optimizer,
    scheduler,
    device,
) -> float:
    """Train for one epoch."""
    model.train()
    total_loss = 0

    progress_bar = tqdm(dataloader, desc="Training")
    for batch in progress_bar:
        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({"loss": loss.item()})

    return total_loss / len(dataloader)


def evaluate(
    model,
    dataloader,
    device,
    categories: list[str],
    threshold: float = 0.5,
) -> dict[str, float]:
    """Evaluate model on validation/test set."""
    model.eval()
    all_predictions = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
            )

            # Apply sigmoid to get probabilities
            probs = torch.sigmoid(outputs.logits)

            # Apply threshold
            predictions = (probs > threshold).float()

            all_predictions.extend(predictions.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_predictions = np.array(all_predictions)
    all_labels = np.array(all_labels)

    # Calculate metrics
    metrics = {
        "hamming_loss": hamming_loss(all_labels, all_predictions),
        "f1_micro": f1_score(all_labels, all_predictions, average="micro"),
        "f1_macro": f1_score(all_labels, all_predictions, average="macro"),
        "f1_samples": f1_score(all_labels, all_predictions, average="samples"),
    }

    # Per-category metrics
    for idx, category in enumerate(categories):
        cat_labels = all_labels[:, idx]
        cat_preds = all_predictions[:, idx]
        metrics[f"f1_{category}"] = f1_score(cat_labels, cat_preds)

    return metrics


def main():
    parser = argparse.ArgumentParser(
        description="Train BERT-based lawsuit classifier",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=REPO_ROOT / "config" / "event_extraction.toml",
        help="Path to config file",
    )
    parser.add_argument(
        "--data",
        type=Path,
        help="Path to training data JSON (default: from config)",
    )
    parser.add_argument(
        "--model",
        type=str,
        help="BERT model name (default: from config)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output directory for trained model (default: from config)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        help="Training batch size (default: from config)",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
        help="Learning rate",
    )
    parser.add_argument(
        "--test-split",
        type=float,
        default=0.2,
        help="Test set split ratio",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume training from checkpoint",
    )
    parser.add_argument(
        "--evaluate",
        action="store_true",
        help="Only evaluate (no training)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    # Load config
    config = load_config(args.config)

    # Determine paths
    data_path = args.data or Path(config.get(
        "training_data_path",
        "data/classification/training_data.json"
    ))
    model_name = args.model or config.get(
        "bert_model",
        "nlpaueb/legal-bert-base-uncased"
    )
    output_dir = args.output or Path(config.get(
        "model_save_path",
        "data/classification/bert_classifier"
    ))
    batch_size = args.batch_size or config.get("bert_batch_size", 8)
    max_length = config.get("bert_max_length", 512)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Check for GPU
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    # Load training data
    logger.info(f"Loading training data from {data_path}")
    texts, labels, categories = load_training_data(data_path)

    # Split data
    train_texts, test_texts, train_labels, test_labels = train_test_split(
        texts, labels, test_size=args.test_split, random_state=42
    )
    logger.info(f"Train: {len(train_texts)}, Test: {len(test_texts)}")

    # Load tokenizer and model
    logger.info(f"Loading model: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    if args.resume and (output_dir / "pytorch_model.bin").exists():
        logger.info(f"Resuming from checkpoint: {output_dir}")
        model = AutoModelForSequenceClassification.from_pretrained(
            output_dir,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )
    else:
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )

    model.to(device)

    # Create datasets
    train_dataset = LawsuitDataset(
        train_texts, train_labels, tokenizer, max_length
    )
    test_dataset = LawsuitDataset(
        test_texts, test_labels, tokenizer, max_length
    )

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )
    test_loader = DataLoader(
        test_dataset, batch_size=batch_size
    )

    if args.evaluate:
        # Evaluate only
        logger.info("Evaluating model...")
        metrics = evaluate(model, test_loader, device, categories)

        print("\n=== Evaluation Results ===")
        for metric, value in metrics.items():
            print(f"{metric}: {value:.4f}")
        return

    # Setup training
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)

    total_steps = len(train_loader) * args.epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    # Training loop
    best_f1 = 0.0
    for epoch in range(args.epochs):
        logger.info(f"\n=== Epoch {epoch + 1}/{args.epochs} ===")

        # Train
        train_loss = train_epoch(
            model, train_loader, optimizer, scheduler, device
        )
        logger.info(f"Average training loss: {train_loss:.4f}")

        # Evaluate
        metrics = evaluate(model, test_loader, device, categories)

        logger.info("\nValidation metrics:")
        for metric, value in metrics.items():
            logger.info(f"  {metric}: {value:.4f}")

        # Save best model
        f1_macro = metrics["f1_macro"]
        if f1_macro > best_f1:
            best_f1 = f1_macro
            logger.info(f"New best F1-macro: {best_f1:.4f}, saving model...")
            model.save_pretrained(output_dir)
            tokenizer.save_pretrained(output_dir)

            # Save config and category mapping
            config_data = {
                "model_name": model_name,
                "categories": categories,
                "max_length": max_length,
                "best_f1_macro": best_f1,
            }
            with open(output_dir / "config.json", "w") as f:
                json.dump(config_data, f, indent=2)

    logger.info(f"\nTraining complete! Best F1-macro: {best_f1:.4f}")
    logger.info(f"Model saved to: {output_dir}")

    print("\n=== Final Test Results ===")
    metrics = evaluate(model, test_loader, device, categories)
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")


if __name__ == "__main__":
    main()
