#!/usr/bin/env python3
"""Train a BERT-based lawsuit classifier from LLM-generated training data.

This script trains a fast BERT-based multilabel classifier using the training
data generated by zero_shot_classifier.py. The resulting model can classify
lawsuits much faster than the LLM-based approach.

Usage:
    # Train using default config
    python scripts/train_bert_classifier.py

    # Train with custom data
    python scripts/train_bert_classifier.py --data data/custom_training.json

    # Train with custom model
    python scripts/train_bert_classifier.py --model nlpaueb/legal-bert-base-uncased

    # Resume training from checkpoint
    python scripts/train_bert_classifier.py --resume

    # Evaluate on test set
    python scripts/train_bert_classifier.py --evaluate

    # Calibrate probabilities against a held-out calibration split
    python scripts/train_bert_classifier.py --calibration-split 0.1

    # Bootstrap ensemble: train 100 models on bootstrap draws of the
    # training set, for bagged predictions + per-category uncertainty
    python scripts/train_bert_classifier.py --bootstrap-iterations 100
"""

import argparse
import json
import logging
import re
import sys
import time
import tomllib
from pathlib import Path
from typing import Any

_TAG_RE = re.compile(r"<[^>]+>")


def _clean(value: Any) -> str:
    """Strip HTML tags and collapse whitespace from a metadata field."""
    return " ".join(_TAG_RE.sub(" ", str(value or "")).split())


# Field name for the LLM-generated summary in a reconciled training row.
SUMMARY_FIELD = "summary"


def build_bert_input_text(result: dict[str, Any], input_field: str = "auto") -> str:
    """Assemble the exact text fed to the BERT tokenizer for one case.

    Single source of truth shared by training
    (scripts/train_bert_classifier.py), summary generation
    (scripts/summarize_cases_for_classification.py, which sizes summaries
    against this) and inference (scripts/classify_lawsuit.py).

    input_field:
        "summary" - always use the LLM summary (raises if absent)
        "excerpt" - always use the raw document excerpt
        "auto"    - summary when present, else the excerpt
    """
    header = [
        f"Caption: {_clean(result.get('caption')) or 'Unknown'}",
        f"Court: {_clean(result.get('court')) or 'Unknown'}",
        f"Case Type: {_clean(result.get('case_type')) or 'Unknown'}",
    ]

    summary = (result.get(SUMMARY_FIELD) or "").strip()
    use_summary = summary and input_field in ("auto", "summary")
    if input_field == "summary" and not summary:
        raise ValueError(
            f"input_field='summary' but case {result.get('case_id')!r} has no "
            f"{SUMMARY_FIELD!r} - run scripts/summarize_cases_for_classification.py"
        )

    if use_summary:
        return "\n".join(header + [f"\nSummary:\n{summary}"])

    parts = list(header)
    if result.get("document_names"):
        parts.append(f"Documents: {', '.join(result['document_names'])}")
    if result.get("text_excerpt"):
        parts.append(f"\nExcerpt:\n{result['text_excerpt']}")
    return "\n".join(parts)

import numpy as np
import torch
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, hamming_loss, f1_score
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)

# Add parent directory to path for imports
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

logger = logging.getLogger(__name__)


class LawsuitDataset(Dataset):
    """Dataset for lawsuit classification."""

    def __init__(
        self,
        texts: list[str],
        labels: list[list[int]],
        tokenizer,
        max_length: int,
    ):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": torch.tensor(label, dtype=torch.float),
        }


def load_config(config_path: Path) -> dict[str, Any]:
    """Load configuration from TOML file."""
    with open(config_path, "rb") as f:
        config = tomllib.load(f)
    return config.get("lawsuit_classification", {})


def load_training_data(
    data_path: Path,
    drop_empty: bool = False,
    input_field: str = "auto",
    exclude_categories: list[str] | None = None,
) -> tuple[list[str], list[list[int]], list[str]]:
    """Load and prepare training data from JSON file.

    Expects the file produced by reconcile_classifications.py
    (--training-output): each result carries a flat "labels" list whose
    categories are the ones the LLM providers agreed on under the chosen
    reconciliation strategy, and (when summaries have been generated and
    merged in) a "summary" field.

    Args:
        data_path: Path to the reconciled training-data JSON.
        drop_empty: If True, skip cases whose reconciled label vector is
            all-zero. Default False - those rows are kept as negative
            examples (needed for calibration and for rare categories).
        input_field: "summary", "excerpt" or "auto" - see
            build_bert_input_text. "summary" skips cases with no summary.
        exclude_categories: Category names to drop from the label space
            entirely (e.g. a category with too few positive examples to
            train on yet). The trained model simply has no head for them;
            the source data is untouched.

    Returns:
        texts: List of input texts (case metadata + summary/excerpt)
        labels: List of multilabel binary vectors
        categories: List of category names
    """
    with open(data_path) as f:
        data = json.load(f)

    exclude_categories = set(exclude_categories or [])
    categories = [c for c in data["metadata"]["categories"] if c not in exclude_categories]
    if exclude_categories:
        logger.info(f"Excluding categories from training: {sorted(exclude_categories)}")
    category_to_idx = {cat: idx for idx, cat in enumerate(categories)}

    texts = []
    labels = []
    n_summary = 0
    n_excerpt = 0
    n_no_summary_skipped = 0

    for result in data["results"]:
        if input_field == "summary" and not (result.get(SUMMARY_FIELD) or "").strip():
            n_no_summary_skipped += 1
            continue

        text = build_bert_input_text(result, input_field=input_field)

        # Build multilabel vector
        label_vector = [0] * len(categories)
        for label_info in result.get("labels", []):
            category = label_info["category"]
            if category in category_to_idx:
                label_vector[category_to_idx[category]] = 1

        if drop_empty and sum(label_vector) == 0:
            continue
        texts.append(text)
        labels.append(label_vector)
        if (result.get(SUMMARY_FIELD) or "").strip() and input_field != "excerpt":
            n_summary += 1
        else:
            n_excerpt += 1

    logger.info(f"Loaded {len(texts)} training examples")
    logger.info(
        f"Input text: {n_summary} from summary, {n_excerpt} from raw excerpt"
        + (f", {n_no_summary_skipped} skipped (no summary)" if n_no_summary_skipped else "")
    )
    logger.info(f"Categories: {categories}")
    log_label_distribution(labels, categories)

    return texts, labels, categories


def log_label_distribution(labels: list[list[int]], categories: list[str]) -> None:
    """Log per-category positive-example counts and share of the set."""
    label_counts = np.array(labels).sum(axis=0)
    total = len(labels)
    for cat, count in zip(categories, label_counts):
        logger.info(f"  {cat}: {int(count)} examples ({count/total*100:.1f}%)")


def bootstrap_resample(
    texts: list[str],
    labels: list[list[int]],
    factor: float,
    seed: int = 42,
) -> tuple[list[str], list[list[int]]]:
    """Enlarge a training set via bootstrap sampling (with replacement).

    factor=2.0 draws a training set twice the original size, each example
    picked independently and uniformly at random with replacement. Apply
    this only to the training split - bootstrapping test or calibration
    data would duplicate examples across the eval set and bias metrics.
    """
    if factor <= 0:
        raise ValueError(f"bootstrap factor must be > 0, got {factor}")
    rng = np.random.default_rng(seed)
    target_size = round(len(texts) * factor)
    indices = rng.integers(0, len(texts), size=target_size)
    return [texts[i] for i in indices], [labels[i] for i in indices]


def train_epoch(
    model,
    dataloader,
    optimizer,
    scheduler,
    device,
) -> float:
    """Train for one epoch."""
    model.train()
    total_loss = 0

    progress_bar = tqdm(dataloader, desc="Training")
    for batch in progress_bar:
        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({"loss": loss.item()})

    return total_loss / len(dataloader)


def run_inference(
    model,
    dataloader,
    device,
    desc: str = "Evaluating",
) -> tuple[np.ndarray, np.ndarray]:
    """Run the model over a dataloader, returning raw logits and true labels."""
    model.eval()
    all_logits = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(dataloader, desc=desc):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(input_ids=input_ids, attention_mask=attention_mask)

            all_logits.append(outputs.logits.cpu().numpy())
            all_labels.append(labels.cpu().numpy())

    return np.concatenate(all_logits), np.concatenate(all_labels)


def fit_platt_scaling(
    logits: np.ndarray,
    labels: np.ndarray,
    categories: list[str],
) -> dict[str, dict[str, float]]:
    """Fit per-category Platt scaling on raw logits and true labels.

    Raw BERT sigmoid outputs tend to be overconfident. This fits a 1D
    logistic regression per category mapping raw logit -> calibrated
    probability (sigmoid(a * logit + b)), so thresholds and reported
    confidences are meaningful. A category with only one class present in
    the calibration set (common for rare categories on a small dataset)
    can't be fit and is left uncalibrated (a=1, b=0).

    logits/labels: arrays shaped (n_examples, n_categories) - either from
    a single model (run_inference) or the mean logit across a bootstrap
    ensemble (see summarize_bootstrap_ensemble).
    """
    calibrators = {}
    for idx, category in enumerate(categories):
        y = labels[:, idx]
        x = logits[:, idx].reshape(-1, 1)
        if len(np.unique(y)) < 2:
            logger.warning(
                f"Calibration: '{category}' has only one class in the "
                "calibration set, leaving uncalibrated"
            )
            calibrators[category] = {"a": 1.0, "b": 0.0}
            continue
        lr = LogisticRegression()
        lr.fit(x, y)
        calibrators[category] = {"a": float(lr.coef_[0][0]), "b": float(lr.intercept_[0])}

    return calibrators


def calibrate_probabilities(
    model,
    dataloader,
    device,
    categories: list[str],
) -> dict[str, dict[str, float]]:
    """Fit per-category Platt scaling on a held-out calibration set."""
    logits, labels = run_inference(model, dataloader, device, desc="Calibrating")
    return fit_platt_scaling(logits, labels, categories)


def apply_calibration(
    logits: np.ndarray,
    categories: list[str],
    calibrators: dict[str, dict[str, float]] | None,
) -> np.ndarray:
    """Convert raw logits to probabilities, applying Platt scaling if given."""
    if not calibrators:
        return 1 / (1 + np.exp(-logits))
    scaled = np.empty_like(logits)
    for idx, category in enumerate(categories):
        params = calibrators[category]
        scaled[:, idx] = params["a"] * logits[:, idx] + params["b"]
    return 1 / (1 + np.exp(-scaled))


def metrics_from_probs(
    probs: np.ndarray,
    all_labels: np.ndarray,
    categories: list[str],
    threshold: float = 0.5,
) -> dict[str, float]:
    """Compute the standard metric set from probabilities and true labels."""
    all_predictions = (probs > threshold).astype(float)

    metrics = {
        "hamming_loss": hamming_loss(all_labels, all_predictions),
        "f1_micro": f1_score(all_labels, all_predictions, average="micro", zero_division=0),
        "f1_macro": f1_score(all_labels, all_predictions, average="macro", zero_division=0),
        "f1_samples": f1_score(all_labels, all_predictions, average="samples", zero_division=0),
    }

    for idx, category in enumerate(categories):
        cat_labels = all_labels[:, idx]
        cat_preds = all_predictions[:, idx]
        metrics[f"f1_{category}"] = f1_score(cat_labels, cat_preds, zero_division=0)

    return metrics


def evaluate(
    model,
    dataloader,
    device,
    categories: list[str],
    threshold: float = 0.5,
    calibrators: dict[str, dict[str, float]] | None = None,
) -> dict[str, float]:
    """Evaluate model on validation/test set.

    calibrators: optional per-category Platt-scaling params from
        calibrate_probabilities(); when given, probabilities are
        sigmoid(a * logit + b) instead of the raw sigmoid(logit).
    """
    logits, all_labels = run_inference(model, dataloader, device)
    probs = apply_calibration(logits, categories, calibrators)
    return metrics_from_probs(probs, all_labels, categories, threshold)


def run_bootstrap_ensemble(
    train_texts: list[str],
    train_labels: list[list[int]],
    test_loader,
    calib_loader,
    tokenizer,
    model_name: str,
    categories: list[str],
    max_length: int,
    batch_size: int,
    device,
    epochs: int,
    learning_rate: float,
    n_iterations: int,
    models_dir: Path,
) -> tuple[np.ndarray, np.ndarray, np.ndarray | None]:
    """Train n_iterations models on independent bootstrap draws of the
    training set, evaluating each on test_loader (and calib_loader, if
    given) as it finishes.

    Each iteration's model is saved to models_dir/bootstrap_XXXX/ and
    marked with a DONE file once its predictions are cached to disk - a
    rerun skips any iteration whose DONE file already exists, so an
    interrupted run (this can take days at high iteration counts) resumes
    instead of restarting.

    Returns (test_logits, test_labels, calib_logits) where test_logits has
    shape (n_iterations, n_test_examples, n_categories) - one row of raw
    logits per bootstrap model - and calib_logits is the analogous stack
    for calib_loader, or None if no calibration split was requested.
    """
    models_dir.mkdir(parents=True, exist_ok=True)

    all_test_logits = []
    all_calib_logits = [] if calib_loader is not None else None
    test_labels = None
    iter_times = []

    for b in range(n_iterations):
        run_dir = models_dir / f"bootstrap_{b:04d}"
        done_marker = run_dir / "DONE"

        if done_marker.exists():
            logger.info(f"Bootstrap {b + 1}/{n_iterations}: already trained, loading cached logits")
            all_test_logits.append(np.load(run_dir / "test_logits.npy"))
            if test_labels is None:
                test_labels = np.load(run_dir / "test_labels.npy")
            if calib_loader is not None:
                all_calib_logits.append(np.load(run_dir / "calib_logits.npy"))
            continue

        start = time.time()
        logger.info(f"Bootstrap {b + 1}/{n_iterations}: training")

        bt_texts, bt_labels = bootstrap_resample(train_texts, train_labels, factor=1.0, seed=b)

        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )
        model.to(device)

        bt_dataset = LawsuitDataset(bt_texts, bt_labels, tokenizer, max_length)
        bt_loader = DataLoader(bt_dataset, batch_size=batch_size, shuffle=True)

        optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)
        total_steps = len(bt_loader) * epochs
        scheduler = get_linear_schedule_with_warmup(
            optimizer,
            num_warmup_steps=int(0.1 * total_steps),
            num_training_steps=total_steps,
        )

        for epoch in range(epochs):
            train_loss = train_epoch(model, bt_loader, optimizer, scheduler, device)
            logger.info(f"  epoch {epoch + 1}/{epochs}: loss {train_loss:.4f}")

        test_logits, test_labels_out = run_inference(
            model, test_loader, device, desc=f"Bootstrap {b + 1} test eval"
        )
        if test_labels is None:
            test_labels = test_labels_out

        run_dir.mkdir(parents=True, exist_ok=True)
        model.save_pretrained(run_dir)
        tokenizer.save_pretrained(run_dir)
        np.save(run_dir / "test_logits.npy", test_logits)
        np.save(run_dir / "test_labels.npy", test_labels_out)

        if calib_loader is not None:
            calib_logits, _ = run_inference(
                model, calib_loader, device, desc=f"Bootstrap {b + 1} calib eval"
            )
            np.save(run_dir / "calib_logits.npy", calib_logits)
            all_calib_logits.append(calib_logits)

        done_marker.touch()
        all_test_logits.append(test_logits)

        del model
        if device.type == "cuda":
            torch.cuda.empty_cache()

        elapsed = time.time() - start
        iter_times.append(elapsed)
        avg = sum(iter_times) / len(iter_times)
        remaining = n_iterations - (b + 1)
        logger.info(
            f"Bootstrap {b + 1}/{n_iterations} done in {elapsed:.1f}s "
            f"(avg {avg:.1f}s/iter, ETA {avg * remaining / 60:.1f} min for "
            f"{remaining} remaining)"
        )

    calib_stack = np.stack(all_calib_logits) if all_calib_logits else None
    return np.stack(all_test_logits), test_labels, calib_stack


def summarize_bootstrap_ensemble(
    test_logits_stack: np.ndarray,
    test_labels: np.ndarray,
    categories: list[str],
    calib_logits_stack: np.ndarray | None = None,
    calib_labels: np.ndarray | None = None,
) -> dict[str, Any]:
    """Aggregate a bootstrap ensemble into a bagged prediction + uncertainty report.

    The bagged probability per case/category is the mean of each bootstrap
    model's sigmoid output; the standard deviation across models is the
    uncertainty estimate. When a calibration set is given, Platt scaling is
    fit once on the mean (bagged) calibration logits/labels and applied to
    the bagged test probabilities.
    """
    test_probs_stack = 1 / (1 + np.exp(-test_logits_stack))  # (B, N, C)
    mean_probs = test_probs_stack.mean(axis=0)
    std_probs = test_probs_stack.std(axis=0)

    calibrators = None
    if calib_logits_stack is not None and calib_labels is not None:
        mean_calib_logits = calib_logits_stack.mean(axis=0)
        calibrators = fit_platt_scaling(mean_calib_logits, calib_labels, categories)
        mean_test_logits = test_logits_stack.mean(axis=0)
        calibrated_probs = apply_calibration(mean_test_logits, categories, calibrators)
    else:
        calibrated_probs = None

    report = {
        "n_iterations": int(test_logits_stack.shape[0]),
        "raw_metrics": metrics_from_probs(mean_probs, test_labels, categories),
        "uncertainty_mean_std": {
            category: float(std_probs[:, idx].mean())
            for idx, category in enumerate(categories)
        },
    }
    if calibrators is not None:
        report["calibration"] = calibrators
        report["calibrated_metrics"] = metrics_from_probs(
            calibrated_probs, test_labels, categories
        )
    return report


def main():
    parser = argparse.ArgumentParser(
        description="Train BERT-based lawsuit classifier",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=REPO_ROOT / "config" / "event_extraction.toml",
        help="Path to config file",
    )
    parser.add_argument(
        "--data",
        type=Path,
        help="Path to training data JSON (default: from config)",
    )
    parser.add_argument(
        "--model",
        type=str,
        help="BERT model name (default: from config)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output directory for trained model (default: from config)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        help="Training batch size (default: from config)",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
        help="Learning rate",
    )
    parser.add_argument(
        "--test-split",
        type=float,
        default=0.2,
        help="Test set split ratio",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume training from checkpoint",
    )
    parser.add_argument(
        "--evaluate",
        action="store_true",
        help="Only evaluate (no training)",
    )
    parser.add_argument(
        "--drop-empty",
        action="store_true",
        help="Skip cases with no positive reconciled label instead of "
        "keeping them as negative examples",
    )
    parser.add_argument(
        "--input-field",
        choices=["auto", "summary", "excerpt"],
        default="auto",
        help="Which case text to feed BERT: the LLM 'summary' (from "
        "scripts/summarize_cases_for_classification.py), the raw document "
        "'excerpt', or 'auto' (summary when present, else excerpt)",
    )
    parser.add_argument(
        "--exclude-categories",
        nargs="+",
        default=[],
        metavar="CATEGORY",
        help="Category name(s) to drop from the label space entirely "
        "(e.g. --exclude-categories class_action) - use for categories "
        "with too few positive examples to train on yet",
    )
    parser.add_argument(
        "--bootstrap-iterations",
        type=int,
        default=0,
        help="Train an ensemble of this many models, each on an "
        "independent bootstrap draw of the training set, and aggregate "
        "them into a bagged prediction + per-category uncertainty report "
        "(mean/std across the ensemble). When > 0, this replaces the "
        "normal single-model train/evaluate flow. 0 (default) disables it.",
    )
    parser.add_argument(
        "--bootstrap-models-dir",
        type=Path,
        help="Directory to save each bootstrap-ensemble model to (default: "
        "from config, kept separate from --output so the single-model "
        "checkpoint isn't mixed in with the ensemble)",
    )
    parser.add_argument(
        "--calibration-split",
        type=float,
        default=0.0,
        help="Fraction of the training set to hold out for per-category "
        "probability calibration (Platt scaling), refit whenever a new "
        "best model is saved. 0 (default) disables calibration.",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    # Load config
    config = load_config(args.config)

    # Determine paths
    data_path = args.data or Path(config.get(
        "reconciled_training_data_path",
        "data/classification/reconciled_training_data.json"
    ))
    model_name = args.model or config.get(
        "bert_model",
        "nlpaueb/legal-bert-base-uncased"
    )
    output_dir = args.output or Path(config.get(
        "model_save_path",
        "data/classification/bert_classifier"
    ))
    batch_size = args.batch_size or config.get("bert_batch_size", 8)
    max_length = config.get("bert_max_length", 512)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Check for GPU
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    # Load training data
    logger.info(f"Loading training data from {data_path}")
    texts, labels, categories = load_training_data(
        data_path,
        drop_empty=args.drop_empty,
        input_field=args.input_field,
        exclude_categories=args.exclude_categories,
    )

    # Split data
    train_texts, test_texts, train_labels, test_labels = train_test_split(
        texts, labels, test_size=args.test_split, random_state=42
    )

    calib_texts, calib_labels = [], []
    if args.calibration_split > 0:
        train_texts, calib_texts, train_labels, calib_labels = train_test_split(
            train_texts, train_labels, test_size=args.calibration_split, random_state=42
        )

    logger.info(
        f"Train: {len(train_texts)}, Test: {len(test_texts)}, "
        f"Calibration: {len(calib_texts)}"
    )

    # Load tokenizer and model
    logger.info(f"Loading model: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    if args.resume and (
        (output_dir / "model.safetensors").exists()
        or (output_dir / "pytorch_model.bin").exists()
    ):
        logger.info(f"Resuming from checkpoint: {output_dir}")
        model = AutoModelForSequenceClassification.from_pretrained(
            output_dir,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )
    else:
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )

    model.to(device)

    # Create datasets
    train_dataset = LawsuitDataset(
        train_texts, train_labels, tokenizer, max_length
    )
    test_dataset = LawsuitDataset(
        test_texts, test_labels, tokenizer, max_length
    )

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )
    test_loader = DataLoader(
        test_dataset, batch_size=batch_size
    )

    calib_loader = None
    if calib_texts:
        calib_dataset = LawsuitDataset(calib_texts, calib_labels, tokenizer, max_length)
        calib_loader = DataLoader(calib_dataset, batch_size=batch_size)

    if args.bootstrap_iterations > 0:
        bootstrap_models_dir = args.bootstrap_models_dir or Path(config.get(
            "bootstrap_models_path",
            "data/classification_bootstrap_models"
        ))
        # Each ensemble iteration builds its own model; the single model
        # loaded above isn't used in this branch.
        del model
        if device.type == "cuda":
            torch.cuda.empty_cache()

        logger.info(
            f"Bootstrap ensemble: {args.bootstrap_iterations} iterations -> "
            f"{bootstrap_models_dir}"
        )
        calib_labels_arr = np.array(calib_labels) if calib_labels else None
        test_logits_stack, test_labels_arr, calib_logits_stack = run_bootstrap_ensemble(
            train_texts,
            train_labels,
            test_loader,
            calib_loader,
            tokenizer,
            model_name,
            categories,
            max_length,
            batch_size,
            device,
            epochs=args.epochs,
            learning_rate=args.learning_rate,
            n_iterations=args.bootstrap_iterations,
            models_dir=bootstrap_models_dir,
        )
        report = summarize_bootstrap_ensemble(
            test_logits_stack,
            test_labels_arr,
            categories,
            calib_logits_stack=calib_logits_stack,
            calib_labels=calib_labels_arr,
        )
        report["categories"] = categories
        report["model_name"] = model_name

        report_path = bootstrap_models_dir / "ensemble_report.json"
        with open(report_path, "w") as f:
            json.dump(report, f, indent=2)

        print("\n=== Bootstrap Ensemble Results (bagged, raw) ===")
        for metric, value in report["raw_metrics"].items():
            print(f"{metric}: {value:.4f}")
        print("\nPer-category uncertainty (mean std across ensemble):")
        for cat, std in report["uncertainty_mean_std"].items():
            print(f"  {cat}: {std:.4f}")
        if "calibrated_metrics" in report:
            print("\n=== Bootstrap Ensemble Results (bagged, calibrated) ===")
            for metric, value in report["calibrated_metrics"].items():
                print(f"{metric}: {value:.4f}")

        logger.info(f"Ensemble report saved to: {report_path}")
        return

    if args.evaluate:
        # Evaluate only
        logger.info("Evaluating model...")
        metrics = evaluate(model, test_loader, device, categories)

        print("\n=== Evaluation Results ===")
        for metric, value in metrics.items():
            print(f"{metric}: {value:.4f}")

        if calib_loader is not None:
            calibrators = calibrate_probabilities(model, calib_loader, device, categories)
            calibrated_metrics = evaluate(
                model, test_loader, device, categories, calibrators=calibrators
            )
            print("\n=== Evaluation Results (calibrated) ===")
            for metric, value in calibrated_metrics.items():
                print(f"{metric}: {value:.4f}")
        return

    # Setup training
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)

    total_steps = len(train_loader) * args.epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    # Training loop
    best_f1 = 0.0
    for epoch in range(args.epochs):
        logger.info(f"\n=== Epoch {epoch + 1}/{args.epochs} ===")

        # Train
        train_loss = train_epoch(
            model, train_loader, optimizer, scheduler, device
        )
        logger.info(f"Average training loss: {train_loss:.4f}")

        # Evaluate
        metrics = evaluate(model, test_loader, device, categories)

        logger.info("\nValidation metrics:")
        for metric, value in metrics.items():
            logger.info(f"  {metric}: {value:.4f}")

        # Save best model
        f1_macro = metrics["f1_macro"]
        if f1_macro > best_f1:
            best_f1 = f1_macro
            logger.info(f"New best F1-macro: {best_f1:.4f}, saving model...")
            model.save_pretrained(output_dir)
            tokenizer.save_pretrained(output_dir)

            # Save category mapping / training metadata alongside the model.
            # NB: a separate filename - "config.json" belongs to
            # model.save_pretrained() and must not be overwritten or the
            # model can't be reloaded.
            config_data = {
                "model_name": model_name,
                "categories": categories,
                "max_length": max_length,
                "input_field": args.input_field,
                "best_f1_macro": best_f1,
            }
            if calib_loader is not None:
                config_data["calibration"] = calibrate_probabilities(
                    model, calib_loader, device, categories
                )
            with open(output_dir / "classifier_meta.json", "w") as f:
                json.dump(config_data, f, indent=2)

    logger.info(f"\nTraining complete! Best F1-macro: {best_f1:.4f}")
    logger.info(f"Model saved to: {output_dir}")

    print("\n=== Final Test Results ===")
    metrics = evaluate(model, test_loader, device, categories)
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")

    if calib_loader is not None:
        calibrators = calibrate_probabilities(model, calib_loader, device, categories)
        calibrated_metrics = evaluate(
            model, test_loader, device, categories, calibrators=calibrators
        )
        print("\n=== Final Test Results (calibrated) ===")
        for metric, value in calibrated_metrics.items():
            print(f"{metric}: {value:.4f}")


if __name__ == "__main__":
    main()
