#!/usr/bin/env python3
"""Train a BERT-based lawsuit classifier from LLM-generated training data.

This script trains a fast BERT-based multilabel classifier using the training
data generated by zero_shot_classifier.py. The resulting model can classify
lawsuits much faster than the LLM-based approach.

Usage:
    # Train using default config
    python scripts/train_bert_classifier.py

    # Train with custom data
    python scripts/train_bert_classifier.py --data data/custom_training.json

    # Train with custom model
    python scripts/train_bert_classifier.py --model nlpaueb/legal-bert-base-uncased

    # Resume training from checkpoint
    python scripts/train_bert_classifier.py --resume

    # Evaluate on test set
    python scripts/train_bert_classifier.py --evaluate
"""

import argparse
import json
import logging
import re
import sys
import tomllib
from pathlib import Path
from typing import Any

_TAG_RE = re.compile(r"<[^>]+>")


def _clean(value: Any) -> str:
    """Strip HTML tags and collapse whitespace from a metadata field."""
    return " ".join(_TAG_RE.sub(" ", str(value or "")).split())


# Field name for the LLM-generated summary in a reconciled training row.
SUMMARY_FIELD = "summary"


def build_bert_input_text(result: dict[str, Any], input_field: str = "auto") -> str:
    """Assemble the exact text fed to the BERT tokenizer for one case.

    Single source of truth shared by training
    (scripts/train_bert_classifier.py), summary generation
    (scripts/summarize_cases_for_classification.py, which sizes summaries
    against this) and inference (scripts/classify_lawsuit.py).

    input_field:
        "summary" - always use the LLM summary (raises if absent)
        "excerpt" - always use the raw document excerpt
        "auto"    - summary when present, else the excerpt
    """
    header = [
        f"Caption: {_clean(result.get('caption')) or 'Unknown'}",
        f"Court: {_clean(result.get('court')) or 'Unknown'}",
        f"Case Type: {_clean(result.get('case_type')) or 'Unknown'}",
    ]

    summary = (result.get(SUMMARY_FIELD) or "").strip()
    use_summary = summary and input_field in ("auto", "summary")
    if input_field == "summary" and not summary:
        raise ValueError(
            f"input_field='summary' but case {result.get('case_id')!r} has no "
            f"{SUMMARY_FIELD!r} - run scripts/summarize_cases_for_classification.py"
        )

    if use_summary:
        return "\n".join(header + [f"\nSummary:\n{summary}"])

    parts = list(header)
    if result.get("document_names"):
        parts.append(f"Documents: {', '.join(result['document_names'])}")
    if result.get("text_excerpt"):
        parts.append(f"\nExcerpt:\n{result['text_excerpt']}")
    return "\n".join(parts)

import numpy as np
import torch
from sklearn.metrics import classification_report, hamming_loss, f1_score
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm
from transformers import (
    AutoModelForSequenceClassification,
    AutoTokenizer,
    get_linear_schedule_with_warmup,
)

# Add parent directory to path for imports
REPO_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO_ROOT))

logger = logging.getLogger(__name__)


class LawsuitDataset(Dataset):
    """Dataset for lawsuit classification."""

    def __init__(
        self,
        texts: list[str],
        labels: list[list[int]],
        tokenizer,
        max_length: int,
    ):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_length = max_length

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, idx):
        text = self.texts[idx]
        label = self.labels[idx]

        encoding = self.tokenizer(
            text,
            max_length=self.max_length,
            padding="max_length",
            truncation=True,
            return_tensors="pt",
        )

        return {
            "input_ids": encoding["input_ids"].squeeze(),
            "attention_mask": encoding["attention_mask"].squeeze(),
            "labels": torch.tensor(label, dtype=torch.float),
        }


def load_config(config_path: Path) -> dict[str, Any]:
    """Load configuration from TOML file."""
    with open(config_path, "rb") as f:
        config = tomllib.load(f)
    return config.get("lawsuit_classification", {})


def load_training_data(
    data_path: Path,
    drop_empty: bool = False,
    input_field: str = "auto",
) -> tuple[list[str], list[list[int]], list[str]]:
    """Load and prepare training data from JSON file.

    Expects the file produced by reconcile_classifications.py
    (--training-output): each result carries a flat "labels" list whose
    categories are the ones the LLM providers agreed on under the chosen
    reconciliation strategy, and (when summaries have been generated and
    merged in) a "summary" field.

    Args:
        data_path: Path to the reconciled training-data JSON.
        drop_empty: If True, skip cases whose reconciled label vector is
            all-zero. Default False - those rows are kept as negative
            examples (needed for calibration and for rare categories).
        input_field: "summary", "excerpt" or "auto" - see
            build_bert_input_text. "summary" skips cases with no summary.

    Returns:
        texts: List of input texts (case metadata + summary/excerpt)
        labels: List of multilabel binary vectors
        categories: List of category names
    """
    with open(data_path) as f:
        data = json.load(f)

    categories = data["metadata"]["categories"]
    category_to_idx = {cat: idx for idx, cat in enumerate(categories)}

    texts = []
    labels = []
    n_summary = 0
    n_excerpt = 0
    n_no_summary_skipped = 0

    for result in data["results"]:
        if input_field == "summary" and not (result.get(SUMMARY_FIELD) or "").strip():
            n_no_summary_skipped += 1
            continue

        text = build_bert_input_text(result, input_field=input_field)

        # Build multilabel vector
        label_vector = [0] * len(categories)
        for label_info in result.get("labels", []):
            category = label_info["category"]
            if category in category_to_idx:
                label_vector[category_to_idx[category]] = 1

        if drop_empty and sum(label_vector) == 0:
            continue
        texts.append(text)
        labels.append(label_vector)
        if (result.get(SUMMARY_FIELD) or "").strip() and input_field != "excerpt":
            n_summary += 1
        else:
            n_excerpt += 1

    logger.info(f"Loaded {len(texts)} training examples")
    logger.info(
        f"Input text: {n_summary} from summary, {n_excerpt} from raw excerpt"
        + (f", {n_no_summary_skipped} skipped (no summary)" if n_no_summary_skipped else "")
    )
    logger.info(f"Categories: {categories}")

    # Print label distribution
    label_counts = np.array(labels).sum(axis=0)
    for cat, count in zip(categories, label_counts):
        logger.info(f"  {cat}: {int(count)} examples ({count/len(texts)*100:.1f}%)")

    return texts, labels, categories


def train_epoch(
    model,
    dataloader,
    optimizer,
    scheduler,
    device,
) -> float:
    """Train for one epoch."""
    model.train()
    total_loss = 0

    progress_bar = tqdm(dataloader, desc="Training")
    for batch in progress_bar:
        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
        )

        loss = outputs.loss
        total_loss += loss.item()

        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        optimizer.step()
        scheduler.step()

        progress_bar.set_postfix({"loss": loss.item()})

    return total_loss / len(dataloader)


def evaluate(
    model,
    dataloader,
    device,
    categories: list[str],
    threshold: float = 0.5,
) -> dict[str, float]:
    """Evaluate model on validation/test set."""
    model.eval()
    all_predictions = []
    all_labels = []

    with torch.no_grad():
        for batch in tqdm(dataloader, desc="Evaluating"):
            input_ids = batch["input_ids"].to(device)
            attention_mask = batch["attention_mask"].to(device)
            labels = batch["labels"].to(device)

            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
            )

            # Apply sigmoid to get probabilities
            probs = torch.sigmoid(outputs.logits)

            # Apply threshold
            predictions = (probs > threshold).float()

            all_predictions.extend(predictions.cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    all_predictions = np.array(all_predictions)
    all_labels = np.array(all_labels)

    # Calculate metrics
    metrics = {
        "hamming_loss": hamming_loss(all_labels, all_predictions),
        "f1_micro": f1_score(all_labels, all_predictions, average="micro", zero_division=0),
        "f1_macro": f1_score(all_labels, all_predictions, average="macro", zero_division=0),
        "f1_samples": f1_score(all_labels, all_predictions, average="samples", zero_division=0),
    }

    # Per-category metrics
    for idx, category in enumerate(categories):
        cat_labels = all_labels[:, idx]
        cat_preds = all_predictions[:, idx]
        metrics[f"f1_{category}"] = f1_score(cat_labels, cat_preds, zero_division=0)

    return metrics


def main():
    parser = argparse.ArgumentParser(
        description="Train BERT-based lawsuit classifier",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    parser.add_argument(
        "--config",
        type=Path,
        default=REPO_ROOT / "config" / "event_extraction.toml",
        help="Path to config file",
    )
    parser.add_argument(
        "--data",
        type=Path,
        help="Path to training data JSON (default: from config)",
    )
    parser.add_argument(
        "--model",
        type=str,
        help="BERT model name (default: from config)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        help="Output directory for trained model (default: from config)",
    )
    parser.add_argument(
        "--epochs",
        type=int,
        default=3,
        help="Number of training epochs",
    )
    parser.add_argument(
        "--batch-size",
        type=int,
        help="Training batch size (default: from config)",
    )
    parser.add_argument(
        "--learning-rate",
        type=float,
        default=2e-5,
        help="Learning rate",
    )
    parser.add_argument(
        "--test-split",
        type=float,
        default=0.2,
        help="Test set split ratio",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Resume training from checkpoint",
    )
    parser.add_argument(
        "--evaluate",
        action="store_true",
        help="Only evaluate (no training)",
    )
    parser.add_argument(
        "--drop-empty",
        action="store_true",
        help="Skip cases with no positive reconciled label instead of "
        "keeping them as negative examples",
    )
    parser.add_argument(
        "--input-field",
        choices=["auto", "summary", "excerpt"],
        default="auto",
        help="Which case text to feed BERT: the LLM 'summary' (from "
        "scripts/summarize_cases_for_classification.py), the raw document "
        "'excerpt', or 'auto' (summary when present, else excerpt)",
    )
    parser.add_argument(
        "--verbose",
        action="store_true",
        help="Enable verbose logging",
    )

    args = parser.parse_args()

    # Setup logging
    logging.basicConfig(
        level=logging.DEBUG if args.verbose else logging.INFO,
        format="%(asctime)s - %(name)s - %(levelname)s - %(message)s",
    )

    # Load config
    config = load_config(args.config)

    # Determine paths
    data_path = args.data or Path(config.get(
        "reconciled_training_data_path",
        "data/classification/reconciled_training_data.json"
    ))
    model_name = args.model or config.get(
        "bert_model",
        "nlpaueb/legal-bert-base-uncased"
    )
    output_dir = args.output or Path(config.get(
        "model_save_path",
        "data/classification/bert_classifier"
    ))
    batch_size = args.batch_size or config.get("bert_batch_size", 8)
    max_length = config.get("bert_max_length", 512)

    output_dir.mkdir(parents=True, exist_ok=True)

    # Check for GPU
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    logger.info(f"Using device: {device}")

    # Load training data
    logger.info(f"Loading training data from {data_path}")
    texts, labels, categories = load_training_data(
        data_path, drop_empty=args.drop_empty, input_field=args.input_field
    )

    # Split data
    train_texts, test_texts, train_labels, test_labels = train_test_split(
        texts, labels, test_size=args.test_split, random_state=42
    )
    logger.info(f"Train: {len(train_texts)}, Test: {len(test_texts)}")

    # Load tokenizer and model
    logger.info(f"Loading model: {model_name}")
    tokenizer = AutoTokenizer.from_pretrained(model_name)

    if args.resume and (
        (output_dir / "model.safetensors").exists()
        or (output_dir / "pytorch_model.bin").exists()
    ):
        logger.info(f"Resuming from checkpoint: {output_dir}")
        model = AutoModelForSequenceClassification.from_pretrained(
            output_dir,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )
    else:
        model = AutoModelForSequenceClassification.from_pretrained(
            model_name,
            num_labels=len(categories),
            problem_type="multi_label_classification",
        )

    model.to(device)

    # Create datasets
    train_dataset = LawsuitDataset(
        train_texts, train_labels, tokenizer, max_length
    )
    test_dataset = LawsuitDataset(
        test_texts, test_labels, tokenizer, max_length
    )

    train_loader = DataLoader(
        train_dataset, batch_size=batch_size, shuffle=True
    )
    test_loader = DataLoader(
        test_dataset, batch_size=batch_size
    )

    if args.evaluate:
        # Evaluate only
        logger.info("Evaluating model...")
        metrics = evaluate(model, test_loader, device, categories)

        print("\n=== Evaluation Results ===")
        for metric, value in metrics.items():
            print(f"{metric}: {value:.4f}")
        return

    # Setup training
    optimizer = torch.optim.AdamW(model.parameters(), lr=args.learning_rate)

    total_steps = len(train_loader) * args.epochs
    scheduler = get_linear_schedule_with_warmup(
        optimizer,
        num_warmup_steps=int(0.1 * total_steps),
        num_training_steps=total_steps,
    )

    # Training loop
    best_f1 = 0.0
    for epoch in range(args.epochs):
        logger.info(f"\n=== Epoch {epoch + 1}/{args.epochs} ===")

        # Train
        train_loss = train_epoch(
            model, train_loader, optimizer, scheduler, device
        )
        logger.info(f"Average training loss: {train_loss:.4f}")

        # Evaluate
        metrics = evaluate(model, test_loader, device, categories)

        logger.info("\nValidation metrics:")
        for metric, value in metrics.items():
            logger.info(f"  {metric}: {value:.4f}")

        # Save best model
        f1_macro = metrics["f1_macro"]
        if f1_macro > best_f1:
            best_f1 = f1_macro
            logger.info(f"New best F1-macro: {best_f1:.4f}, saving model...")
            model.save_pretrained(output_dir)
            tokenizer.save_pretrained(output_dir)

            # Save category mapping / training metadata alongside the model.
            # NB: a separate filename - "config.json" belongs to
            # model.save_pretrained() and must not be overwritten or the
            # model can't be reloaded.
            config_data = {
                "model_name": model_name,
                "categories": categories,
                "max_length": max_length,
                "input_field": args.input_field,
                "best_f1_macro": best_f1,
            }
            with open(output_dir / "classifier_meta.json", "w") as f:
                json.dump(config_data, f, indent=2)

    logger.info(f"\nTraining complete! Best F1-macro: {best_f1:.4f}")
    logger.info(f"Model saved to: {output_dir}")

    print("\n=== Final Test Results ===")
    metrics = evaluate(model, test_loader, device, categories)
    for metric, value in metrics.items():
        print(f"{metric}: {value:.4f}")


if __name__ == "__main__":
    main()
